sudo: required
services:
  - docker
before_install:
  - pip install codecov
install: pip install -r req-test.txt
language: python
python:
  - "3.5"
script: py.test --cov=. tests/
after_success:
  - codecov
