data:
    hostname: data
    image: base
    command: start
    volumes:
        - "./container_shared:/container_shared"
        - "./docker/base/config:/config"
        - /data
    entrypoint: ['python3', '/config/run.py']
