proxy:
  hostname: proxy
  image: base
  command: start
  volumes_from:
      - data-container
  entrypoint: ['python3', '/config/run.py']

postgres:
    hostname: postgres
    image: postgres
    command: start
    volumes_from:
        - proxy
    volumes:
        - "./container_shared:/container_shared"
        - "./docker/postgres/config:/config"
    entrypoint: ['python3', '/config/run.py']
    environment:
        PGDATA: /data/postgres
    env_file: env.txt
    ports:
        - "5433:5432"

django:
    hostname: django
    image: django-python3
    entrypoint: ['python3', '/config/run.py']
    command: start_uwsgi
    volumes_from:
        - proxy
    volumes:
        - "./src:/src"
        - "./docker/django-python3/config:/config"
        - "./container_shared:/container_shared"
    links:
        - "postgres:postgres"
    environment:
        PYTHONPATH: /src
        DJANGO_SETTINGS_MODULE: core.settings
        PYTHONUNBUFFERED: true
    env_file: env.txt

nginx:
    hostname: nginx
    image: nginx
    entrypoint: ['python3', '/config/run.py']
    command: start
    volumes_from:
        - proxy
    volumes:
        - "./container_shared:/container_shared"
        - "./docker/nginx/config:/config"
    links:
        - "django:django"
    ports:
        - "8000:8080"
