data:
    hostname: data
    image: base
    command: start
    volumes:
        - "./docker/base/config:/config"
        - /data
    entrypoint: ['python3', '/config/run.py']


postgres:
    hostname: postgres
    image: postgres
    command: start
    volumes_from:
        - data
    volumes:
        - "./docker/postgres/config:/config"
    entrypoint: ['python3', '/config/run.py']
    environment:
        PGDATA: /data/postgres
    env_file: env.txt
    ports:
        - "5433:5432"


django:
    hostname: django
    image: django-python3
    entrypoint: ['python3', '/config/run.py']
    command: start_uwsgi
    volumes_from:
        - data
    volumes:
        - "./src:/src"
        - "./docker/django-python3/config:/config"
        - "./container_shared:/container_shared"
    links:
        - "postgres:postgres"
    environment:
        PYTHONPATH: /src
        DJANGO_SETTINGS_MODULE: core.settings
        PYTHONUNBUFFERED: true
    env_file: env.txt


nginx:
    hostname: nginx
    image: nginx
    entrypoint: ['python3', '/config/run.py']
    command: start
    volumes_from:
        - data
    volumes:
        - "./docker/nginx/config:/config"
    links:
        - "django:django"
    ports:
        - "80:8080"