data:
    hostname: {{cookiecutter.repo_name}}-data
    image: {{cookiecutter.repo_name}}-base
    command: start
    container_name: {{cookiecutter.repo_name}}-data
    volumes:
        - "./container_shared:/container_shared"
        - "./docker/base/config:/config"
        - /data
    entrypoint: ['python3', '/config/run.py']
