proxy:
  hostname: {{cookiecutter.repo_name}}-proxy
  image: {{cookiecutter.repo_name}}-base
  command: start
  volumes_from:
      - {{cookiecutter.repo_name}}-data
  entrypoint: ['python3', '/config/run.py']

postgres:
    hostname: {{cookiecutter.repo_name}}-postgres
    image: {{cookiecutter.repo_name}}-postgres
    command: start
    volumes_from:
        - proxy
    volumes:
        - "./docker/postgres/config:/config"
        - "./container_shared:/container_shared"
    log_opt:
        max-size: "5m"
        max-file: "1"
    entrypoint: ['python3', '/config/run.py']
    environment:
        PGDATA: /data/postgres
    env_file: env.txt
    ports:
        - "5433:5432"

django:
    hostname: {{cookiecutter.repo_name}}-django
    image: {{cookiecutter.repo_name}}-django-python3
    entrypoint: ['python3', '/config/run.py']
    command: start_runserver
    volumes_from:
        - proxy
    volumes:
        - "./src:/src"
        - "./docker/django-python3/config:/config"
        - "./container_shared:/container_shared"
    links:
        - "postgres:postgres"
    log_opt:
        max-size: "5m"
        max-file: "1"
    environment:
        PYTHONPATH: /src
        DJANGO_SETTINGS_MODULE: core.settings
        PYTHONUNBUFFERED: "true"
    env_file: env.txt
    ports:
        - "80:8000"

nodejs:
    hostname: {{cookiecutter.repo_name}}-nodejs
    image: {{cookiecutter.repo_name}}-nodejs
    command: start
    volumes_from:
        - proxy
    volumes:
        - "./docker/nodejs/config:/config"
        - "./container_shared:/container_shared"
        - "./react:/react"
    log_opt:
        max-size: "5m"
        max-file: "1"
    entrypoint: ['python3', '/config/run.py']
    env_file: env.txt
