version: '2'

volumes:
  {{cookiecutter.repo_name}}-data-volume:
    driver: local

services:
  postgres:
      hostname: {{cookiecutter.repo_name}}-postgres
      image: {{cookiecutter.repo_name}}-postgres
      command: start
      volumes:
          - {{cookiecutter.repo_name}}-data-volume:/data
          - "./container_shared:/container_shared"
          - "./docker/postgres/config:/config"
      logging:
        options:
            max-size: "5m"
            max-file: "1"
      entrypoint: ['python3', '/config/run.py']
      environment:
          PGDATA: /data/postgres
      env_file: .secret
      ports:
          - "5433:5432"

  django:
      hostname: {{cookiecutter.repo_name}}-django
      image: {{cookiecutter.repo_name}}-django-python3
      entrypoint: ['python3', '/config/run.py']
      command: start_uwsgi
      user: developer
      volumes:
          - {{cookiecutter.repo_name}}-data-volume:/data
          - "./src:/src"
          - "./docker/django-python3/config:/config"
          - "./container_shared:/container_shared"
      links:
          - "postgres:postgres"
      logging:
        options:
            max-size: "5m"
            max-file: "1"
      environment:
          PYTHONPATH: /src
          DJANGO_SETTINGS_MODULE: core.settings
          PYTHONUNBUFFERED: "True"
          DEBUG: "False"
      env_file: .secret

  nginx:
      hostname: {{cookiecutter.repo_name}}-nginx
      image: {{cookiecutter.repo_name}}-nginx
      entrypoint: ['python3', '/config/run.py']
      command: start
      volumes:
          - {{cookiecutter.repo_name}}-data-volume:/data
          - "./container_shared:/container_shared"
          - "./docker/nginx/config:/config"
      links:
          - "django:django"
      logging:
        options:
            max-size: "5m"
            max-file: "1"
      ports:
          - "80:8080"

  {% if cookiecutter.use_react == 'True' -%}
  nodejs:
      hostname: {{cookiecutter.repo_name}}-nodejs
      image: {{cookiecutter.repo_name}}-nodejs
      command: start_build
      volumes:
          - {{cookiecutter.repo_name}}-data-volume:/data
          - "./docker/nodejs/config:/config"
          - "./container_shared:/container_shared"
          - "./react:/react"
          - "./src:/src"
      logging:
        options:
            max-size: "5m"
            max-file: "1"
      entrypoint: ['python3', '/config/run.py']
      env_file: .secret
{% endif -%}
